### PR TITLE
Data for the first tests

### PR DESCRIPTION
**Pull request by thibauthourlier**
I've decided of a file structure without asking. This is the main reason for doing a PR and not a simple push. I did not added the fasta files because I think it's adding data we don't need but we probably need a script or to add clear information on howe to get the fasta. I'm happy for the fasta to be added if people think it's better

### CODE REVIEW

**Comment by williamstark01** [comment]
This is an excellent PR. The data lists should be a great starting point and the documentation is neat and clear. I agree that uploading the FASTA files isn't a good option, as they would just bloat the repository and can be easily downloaded and generated at will. A small nitpick, maybe the *.lst files could be CSV files instead?

**Comment by thibauthourlier** [comment]
I'll change it csv. I like to use lst when I have only one column which was supposed to be and then I thought let's add the gene name so we can see if we have the same gene or not...

**Comment by williamstark01** [comment]
That makes sense, as soon as you had the file it wasn't easy to think of a filetype change when editing it.

**Comment by williamstark01** [comment]
Looks good to me.

**Review by ens-ftricomi — APPROVED** [review]
The changes are good for me

**Review by kbillis — COMMENTED** [review]
Thank you Thibaut for the examples

**Pull request merged**
